site_name: VSE EasyLoader v6.0 Documentation
site_url: ""
use_directory_urls: false
nav:
    - Home: index.md
    - 'Basics': 2basics.md
    - 'Features': 3features.md
    - 'Advanced': 4advanced.md
    - 'FAQ': 6faqs.md
    - About: 7about.md
theme:
    name: material
    nav_style: dark
    locale: en
    logo: img/logo.png
    features:
      - navigation.instant
      - navigation.tabs
      - toc.integrate
      - navigation.expand
      - navigation.top
      - search.highlight
    palette:
      scheme: slate
      primary: red
      accent: red
    hide:
      - toc
plugins: 
  - offline
  - search:
        lang: en
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
        permalink: "#"
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
